"""Add qr_code_key to User model

Revision ID: 3df11682aba5
Revises: da252004ec84
Create Date: 2026-01-18 11:33:20.476021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df11682aba5'
down_revision = 'da252004ec84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_key', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['qr_code_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('qr_code_key')

    # ### end Alembic commands ###
