"""Add online status and typing features to User

Revision ID: 48934e4e14e9
Revises: c79d37e346ae
Create Date: 2026-01-13 16:34:44.799306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48934e4e14e9'
down_revision = 'c79d37e346ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_typing_now', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_typing_now')

    # ### end Alembic commands ###
