"""Add Community features: posts, likes, followers

Revision ID: bcf455e5dbff
Revises: de40259de243
Create Date: 2026-01-08 16:03:04.723850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf455e5dbff'
down_revision = 'de40259de243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('match_explanation')
        batch_op.drop_column('match_score')

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('optimized_text')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('message_job_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['recipient_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
        batch_op.drop_column('job_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('headline', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('headline')
        batch_op.drop_column('location_name')
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_job_id_fkey'), 'job', ['job_id'], ['id'])

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optimized_text', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_explanation', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
